import os from 'os';
import { app, BrowserWindow, ipcMain, nativeTheme, shell } from 'electron';
import { RazerWatcher } from './watcher/razer_watcher';
import { SynapseV4LogDir } from './watcher/synapse4_files';
import TrayManager from './tray_manager';
import { IconRenderer } from './icon_renderer';
import { BatteryNotifier, showNotification } from './notifier';
import { watchTaskbarTheme } from './taskbar_theme';
import { getSettings, loadSettings, settingsChanges } from './settings_manager';
import type { AppInfo, IconPreviewRequest } from './shared_types';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const GITHUB_URL = 'https://github.com/sanraith/razer-taskbar';

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-var-requires
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Only one tray icon: a second launch just opens the settings of the running instance.
if (!app.requestSingleInstanceLock()) {
  app.quit();
}

// Squirrel's Start menu shortcut uses this AppUserModelID; notifications need it to match.
app.setAppUserModelId(app.isPackaged ? 'com.squirrel.razer_taskbar.razer-taskbar' : process.execPath);

const iconRenderer = new IconRenderer();
const notifier = new BatteryNotifier();
let settingsWindow: BrowserWindow | null = null;
let trayManager: TrayManager | null = null;
let razerWatcher: RazerWatcher | null = null;
let stopThemeWatch: (() => void) | null = null;
let lightTaskbar = false;

/** Mica needs Windows 11 22H2 (build 22621) or newer. */
function supportsMica(): boolean {
  if (process.platform !== 'win32') { return false; }
  const build = parseInt(os.release().split('.')[2] ?? '0');
  return build >= 22621;
}

function titleBarOverlay() {
  return {
    color: 'rgba(0,0,0,0)',
    symbolColor: nativeTheme.shouldUseDarkColors ? '#ffffff' : '#1b1b1b',
    height: 44,
  };
}

function openSettingsWindow(): void {
  if (settingsWindow && !settingsWindow.isDestroyed()) {
    if (settingsWindow.isMinimized()) { settingsWindow.restore(); }
    settingsWindow.show();
    settingsWindow.focus();
    return;
  }

  const mica = supportsMica();
  settingsWindow = new BrowserWindow({
    width: 780,
    height: 760,
    minWidth: 560,
    minHeight: 520,
    show: false,
    title: 'Razer Taskbar',
    autoHideMenuBar: true,
    backgroundColor: mica ? '#00000000' : (nativeTheme.shouldUseDarkColors ? '#202020' : '#f3f3f3'),
    ...(mica ? { backgroundMaterial: 'mica' as const } : {}),
    titleBarStyle: 'hidden',
    titleBarOverlay: titleBarOverlay(),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      sandbox: true,
    },
  });
  settingsWindow.removeMenu();
  settingsWindow.once('ready-to-show', () => settingsWindow?.show());
  settingsWindow.on('closed', () => { settingsWindow = null; });
  // Open links in the default browser, never inside the app.
  settingsWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (url.startsWith('https://')) { void shell.openExternal(url); }
    return { action: 'deny' };
  });
  settingsWindow.webContents.on('will-navigate', e => e.preventDefault());
  void settingsWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
}

function broadcastDevices(): void {
  if (settingsWindow && !settingsWindow.isDestroyed() && razerWatcher) {
    settingsWindow.webContents.send('devicesChanged', razerWatcher.listDevices());
  }
}

function registerIpc(): void {
  ipcMain.handle('getDevices', () => razerWatcher?.listDevices() ?? []);
  ipcMain.handle('getAppInfo', (): AppInfo => ({
    version: app.getVersion(),
    supportsMica: supportsMica(),
    isDarkMode: nativeTheme.shouldUseDarkColors,
    lightTaskbar,
  }));
  ipcMain.handle('renderIcon', (_, r: IconPreviewRequest) => iconRenderer.renderDataUrl({
    style: r.style === 'number' ? 'number' : 'battery',
    percent: typeof r.percent === 'number' ? r.percent : null,
    charging: !!r.charging,
    off: !!r.off,
    low: !!r.low,
    lightTaskbar: !!r.lightTaskbar,
  }, Number(r.size) || 32));
  ipcMain.handle('sendTestNotification', () => {
    showNotification({ title: 'Razer Taskbar', body: 'Notifications are working. You will be alerted when your battery runs low.' });
  });
  ipcMain.handle('openExternal', async (_, target: 'github' | 'logs') => {
    if (target === 'github') { await shell.openExternal(GITHUB_URL); }
    if (target === 'logs') { await shell.openPath(SynapseV4LogDir); }
  });
}

app.on('second-instance', () => openSettingsWindow());

// Keep running in the tray when the settings window closes.
app.on('window-all-closed', () => { /* do not quit */ });

app.on('ready', async () => {
  registerIpc();

  let isFirstTimeLaunch = false;
  settingsChanges.on('_defaultSettingsCreated', () => isFirstTimeLaunch = true);
  settingsChanges.on('runAtStartup', value => app.setLoginItemSettings({ openAtLogin: value }));
  await loadSettings();

  await iconRenderer.init();
  trayManager = new TrayManager(iconRenderer, [
    { label: 'Settings…', click: () => openSettingsWindow() },
    { label: 'Quit', click: () => quit() },
  ], () => openSettingsWindow());
  await trayManager.init();

  const refreshTray = (): void => { void trayManager?.update(); };
  settingsChanges.on('displayChargingState', refreshTray);
  settingsChanges.on('showPercentage', refreshTray);
  settingsChanges.on('shownDeviceHandle', refreshTray);
  settingsChanges.on('lowBatteryThreshold', refreshTray);

  nativeTheme.on('updated', () => {
    if (settingsWindow && !settingsWindow.isDestroyed()) {
      settingsWindow.setTitleBarOverlay(titleBarOverlay());
    }
  });
  stopThemeWatch = watchTaskbarTheme(light => {
    lightTaskbar = light;
    trayManager?.setLightTaskbar(light);
  });

  razerWatcher = new RazerWatcher(devices => {
    trayManager?.setDevices(devices);
    notifier.onDevicesChanged(devices.values(), getSettings());
    broadcastDevices();
  });
  razerWatcher.initialize();
  razerWatcher.stopAndStart();

  if (isFirstTimeLaunch) { openSettingsWindow(); }
});

function quit() {
  stopThemeWatch?.();
  razerWatcher?.dispose();
  trayManager?.dispose();
  iconRenderer.dispose();
  app.quit();
}
